name: $(BuildDefinitionName)_$(SourceBranchName)_$(Build.Reason)_1.$(Year:yy)$(DayOfYear).$(Hours)$(Minutes)

resources:
 repositories:
   - repository: self

pool:
  vmImage: 'windows-latest'

trigger:
  batch : true
  branches:
    include:
    - /*
  paths:
    exclude:
    - README.md

pr:
  paths:
    exclude:
    - README.md

variables:
  - name : BuildPlatform
    value: 'any cpu'
  - name : BuildConfiguration
    value: 'release'
  - name : Solution
    value: '**\*.sln'

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: buildjob
        displayName: Build Job
        steps:
          - checkout: self
            submodules: true
    
          - task: NuGetToolInstaller@0
            displayName: 'Use NuGet 5.5.1'
            inputs:
              versionSpec: 5.5.1

          - task: NuGetCommand@2
            displayName: 'NuGet restore'
            inputs:
              restoreSolution: '$(Solution)'

          - task: VSBuild@1
            displayName: Build Solution
            inputs:
              solution: $(Solution)
              vsVersion: latest
              platform: $(BuildPlatform)
              configuration: $(BuildConfiguration)
              maximumCpuCount: true
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

          - task: CopyFiles@2
            displayName: 'Copy Packaged files'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)\'
              Contents: |
                        **\bin\$(BuildConfiguration)\**
                        deployPackages.json
                        **/cdsunpack*/**
                        **/ReferenceData/**
                        **/Scripts/**
                        **/map.xml
                        **/EnvironmentVariables/**
                        !**/node_modules/**
              TargetFolder: '$(build.artifactstagingdirectory)\'

          - task: PublishPipelineArtifact@1
            displayName: Publish Pipeline Artifacts
            inputs:
              path: $(System.artifactstagingdirectory)
              artifact: drop
                          
      - job: testjob
        displayName: Test Job
        dependsOn: buildjob
        steps:  
          - download: current

          - task: VSTest@2
            displayName: Run Unit Tests
            inputs:
              testSelector: testAssemblies
              testAssemblyVer2: |
                **\Plugins*\**\*test*.dll
                !**\*TestAdapter.dll
                !**\obj\**
              searchFolder: $(Pipeline.Workspace)
              codeCoverageEnabled: true
              runInParallel: true
              runOnlyImpactedTests: true

  - stage: Deployment_Staging
    
    displayName: Deployment Staging
    dependsOn: 'Build'
    condition: succeeded()
    jobs:
    - deployment: DeployJob      
      displayName: Deployment Staging 
      environment: 'Deployment Staging'
      variables:
        - group: replaceRepo.D365CDEnvironment
      strategy:
        runOnce:
          deploy:
            steps:
            - task: PowerShell@2
              displayName: 'Deploy Solution'
              inputs:
                targetType: filePath
                filePath: '$(Pipeline.Workspace)/drop/Solutions/bin/Release/Scripts/SolutionDeploy.ps1'
                arguments: '-DeployServerUrl $(d365url) -UserName $(d365username) -Password $(d365password) -PipelinePath $(Pipeline.Workspace)'
#### ----- Uncomment this block to Enable Azure ARM Template Deployment ------
#    - deployment: AzureJob      
#      displayName: Azure Function App 
#      environment: 'Deployment Staging'
#      variables:
#        - group: replaceRepo.D365CDEnvironment
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#            - task: AzureResourceManagerTemplateDeployment@3
#              displayName: 'ARM Template deployment: $(AzureResourceGroup) scope'
#              inputs:
#                deploymentScope: 'Resource Group'
#                azureResourceManagerConnection: 'replaceRepo-Azure'  #Make sure you create this connection in Azure DevOps under Project / Service Connections
#                subscriptionId: '$(AzureSubscriptionId)'
#                action: 'Create Or Update Resource Group'
#                resourceGroupName: '$(AzureResourceGroup)'
#                location: '$(Location)'
#                templateLocation: 'Linked artifact'
#                csmFile: '$(Pipeline.Workspace)/drop/AzureResources/azuredeploy.json'
#                csmParametersFile: '$(Pipeline.Workspace)/drop/AzureResources/azuredeploy.parameters.json'
#                overrideParameters: '-appInsightsName "$(AzureAppInsightsName)" -appInsightsLocation "$(AzureLocation)" -storageAccountName "$(AzureStorageAccountName)" -storageAccountSku "Standard_LRS" -functionAppName "$(AzureFunctionAppName)" -webAppName "$(AzureWebAppName)" -workspaceName "$(WorkspaceName)" -keyVaultName "$(AzureKeyVaultName)"'
#                deploymentMode: 'Incremental'
#                deploymentOutputs: 'armoutputs'

#            - task: AzureRmWebAppDeployment@4
#              displayName: 'Azure App Service Deploy: $(AzureWebAppName)'
#              inputs:
#                ConnectionType: 'AzureRM'
#                azureSubscription: 'replaceRepo-Azure'
#                appType: functionApp
#                WebAppName: '$(AzureFunctionAppName)'
#                packageForLinux: '$(Pipeline.Workspace)/drop/replaceRepo.zip'
#                #AppSettings: '-PowerAppsPortalConfig:Domain "$(PowerAppsPortalDomain)" -PowerAppsPortalConfig:ApplicationId "$(PowerAppsPortalApplicationId)" -AzureStorageConfig:ContainerName "$(AzureStorageContainerName)"'

#### ----- Uncomment this block to Enable Test Environment Stage Deployment ------
# - stage: Test
    
#    displayName: Test
#    dependsOn: 'Deployment_Staging'
#    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'),notIn(variables['Build.Reason'], 'IndividualCI', 'BatchedCI','PullRequest'))
#    jobs:
#    - deployment: DeployJob      
#      displayName: Test 
#      environment: 'Test'
#      variables:
#        - group: replaceRepo.D365TestEnvironment
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#            - task: PowerShell@2
#              displayName: 'Deploy Solution'
#              inputs:
#                targetType: filePath
#                filePath: '$(Pipeline.Workspace)/drop/Solutions/bin/Release/Scripts/SolutionDeploy.ps1'
#                arguments: '-DeployServerUrl $(d365url) -UserName $(d365username) -Password $(d365password) -PipelinePath $(Pipeline.Workspace)'

#    - deployment: AzureJob      
#      displayName: Azure Function App 
#      environment: 'Test'
#      variables:
#        - group: replaceRepo.D365TestEnvironment
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#            - task: AzureResourceManagerTemplateDeployment@3
#              displayName: 'ARM Template deployment: $(AzureResourceGroup) scope'
#              inputs:
#                deploymentScope: 'Resource Group'
#                azureResourceManagerConnection: 'replaceRepo-Azure'  #Make sure you create this connection in Azure DevOps under Project / Service Connections
#                subscriptionId: '$(AzureSubscriptionId)'
#                action: 'Create Or Update Resource Group'
#                resourceGroupName: '$(AzureResourceGroup)'
#                location: '$(Location)'
#                templateLocation: 'Linked artifact'
#                csmFile: '$(Pipeline.Workspace)/drop/AzureResources/azuredeploy.json'
#                csmParametersFile: '$(Pipeline.Workspace)/drop/AzureResources/azuredeploy.parameters.json'
#                overrideParameters: '-appInsightsName "$(AzureAppInsightsName)" -appInsightsLocation "$(AzureLocation)" -storageAccountName "$(AzureStorageAccountName)" -storageAccountSku "Standard_LRS" -functionAppName "$(AzureFunctionAppName)" -webAppName "$(AzureWebAppName)" -workspaceName "$(WorkspaceName)" -keyVaultName "$(AzureKeyVaultName)"'
#                deploymentMode: 'Incremental'
#                deploymentOutputs: 'armoutputs'

#            - task: AzureRmWebAppDeployment@4
#              displayName: 'Azure App Service Deploy: $(AzureWebAppName)'
#              inputs:
#                ConnectionType: 'AzureRM'
#                azureSubscription: 'replaceRepo-Azure'
#                appType: functionApp
#                WebAppName: '$(AzureFunctionAppName)'
#                packageForLinux: '$(Pipeline.Workspace)/drop/replaceRepo.zip'
#                #AppSettings: '-PowerAppsPortalConfig:Domain "$(PowerAppsPortalDomain)" -PowerAppsPortalConfig:ApplicationId "$(PowerAppsPortalApplicationId)" -AzureStorageConfig:ContainerName "$(AzureStorageContainerName)"'